app/controllers/blacklight_cornell_requests/request_controller.rb
app/models/blacklight_cornell_requests/request.rb

Use holdings data stored in session (if available) (closes #52)

Merge Discoveryaccess-2684

---

app/assets/javascripts/blacklight_cornell_requests/requests.js.coffee
app/assets/stylesheets/blacklight_cornell_requests/request.css
app/views/shared/_volume_select.html.haml

Add a progress spinner to volume selection views

---

app/controllers/blacklight_cornell_requests/request_controller.rb
app/models/blacklight_cornell_requests/request.rb
app/models/blacklight_cornell_requests/work.rb
app/views/blacklight_cornell_requests/request/document_delivery.html.haml

A fix for https://culibrary.atlassian.net/browse/DISCOVERYACCESS-3552

Jgr25 scanit

---

app/controllers/blacklight_cornell_requests/request_controller.rb

remove hack to authenticate with my netid

---

app/controllers/blacklight_cornell_requests/request_controller.rb
app/models/blacklight_cornell_requests/request.rb

Remove unnecessary Request::SCANIT field

Discoveryaccess 3552 continued

---

app/assets/javascripts/blacklight_cornell_requests/requests.js.coffee
app/controllers/blacklight_cornell_requests/request_controller.rb
app/views/blacklight_cornell_requests/request/_bd_notification.html.haml
app/views/blacklight_cornell_requests/request/bd.html.haml
app/views/shared/_request_options.html.haml

New status message for BD requests & disabling of submit button

Merge changes for DISCOVERYACCESS-3829

---

lib/blacklight_cornell_requests/version.rb
release_notes.md
spec/dummy/app/views/layouts/blacklight.html.erb

Point release for Blacklight 7 support.

release v3.0.3

---

app/models/blacklight_cornell_requests/delivery_method.rb
lib/blacklight_cornell_requests/version.rb
release_notes.md

Update mann special delivery method to reflect new voyager location codes.

Mann update

---

app/controllers/blacklight_cornell_requests/request_controller.rb
lib/blacklight_cornell_requests/version.rb
release_notes.md

Added extra js to ensure the window.location call doesn't display in the browser.

DISCOVERYACCESS-4225

---

app/controllers/blacklight_cornell_requests/request_controller.rb
app/helpers/blacklight_cornell_requests/request_helper.rb
app/views/shared/_reqpu.html.haml
app/views/shared/_reqpu_bd.html.haml
lib/blacklight_cornell_requests/version.rb
release_notes.md

Additional logic for displaying special delivery options

---

app/models/blacklight_cornell_requests/volume.rb
lib/blacklight_cornell_requests/version.rb
release_notes.md

Expanded Volume attr_reader to include enum, chron and year.

DISCOVERYACCESS-5887

---

app/controllers/blacklight_cornell_requests/request_controller.rb
app/models/blacklight_cornell_requests/request.rb
app/views/shared/_request_options.html.haml
config/routes.rb
lib/blacklight_cornell_requests/version.rb
release_notes.md

Add Mann Special to the alternate delivery methods when the user chooses another method.

DISCOVERYACCESS-5113

---

app/models/blacklight_cornell_requests/delivery_method.rb
lib/blacklight_cornell_requests/version.rb
release_notes.md

Allow ILL requests for 'in transit on hold' items.

DISCOVERYACCESS-4929

---

app/controllers/blacklight_cornell_requests/request_controller.rb
lib/blacklight_cornell_requests/version.rb
release_notes.md

Trap the RecordNotFound exceptions when there's a bad or missing bibid.

DISCOVERYACCESS-5863

---

app/views/shared/_reqpu.html.haml
lib/blacklight_cornell_requests/version.rb
release_notes.md

Modified the list of delivery libraries presented when requesting, in response to COVID-19 pickup location changes.

Pickup location changes

---

app/assets/javascripts/blacklight_cornell_requests/requests.js.coffee
lib/blacklight_cornell_requests/version.rb
release_notes.md

Had to override the suppressPickup method for temp Covid locations.

Another location update

---

app/controllers/blacklight_cornell_requests/request_controller.rb
app/views/shared/_reqac.html.haml
app/views/shared/_reqpu.html.haml
lib/blacklight_cornell_requests/version.rb
release_notes.md

Don't allow users to make requests from currently "invalid" locations.

Merge Covid-19 related change

---

app/controllers/blacklight_cornell_requests/request_controller.rb
app/models/blacklight_cornell_requests/cul_borrow_direct.rb
app/views/shared/_reqpu_bd.html.haml
lib/blacklight_cornell_requests/version.rb
release_notes.md

Use the new Borrow Direct 'Add Request' API.

Discoveryaccess 6890

---

app/controllers/blacklight_cornell_requests/request_controller.rb
lib/blacklight_cornell_requests/version.rb
release_notes.md

This PR includes the fix for DISCOVERYACCESS-6967: improve BD error messages.

improve BD error messaging

---

app/controllers/blacklight_cornell_requests/request_controller.rb
app/models/blacklight_cornell_requests/cul_borrow_direct.rb
app/views/shared/_reqpu_bd.html.haml
lib/blacklight_cornell_requests/version.rb
release_notes.md

BD API Reversion

---

app/models/blacklight_cornell_requests/delivery_method.rb
release_notes.md

https://culibrary.atlassian.net/browse/DACCESS-202
Caitlin confirmed that users should be able to request Paged materials from ILL/ReShare.

DACCESS-202: Enable ILL requests for Paged items

---

Gemfile
blacklight_cornell_requests.gemspec
lib/blacklight_cornell_requests/version.rb
release_notes.md

* Clean up Gemfile, gemspec
* Specify edge version in Gemfile
* Bump to v5.0; release notes

Merge changes for v5.0

---

app/assets/javascripts/blacklight_cornell_requests/requests.js.coffee
release_notes.md

https://culibrary.atlassian.net/browse/DACCESS-206

DACCESS-206 : Fix bug disabling submit button after error
